name: Deploy Theme (Stable)
on:
  push:
    branches:
      - stable
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
        env:
          RUNNER_TEMP: "/tmp/"
      - run: npm install --global gulp-cli
      - run: npm install
      - run: npm run build --if-present
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@master
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          exclude: "node_modules/*"
