name: Deploy Theme (Stable)
on:
  push:
    branches:
      - stable
jobs:
  deploy:
    runs-on: ubuntu-18.04
    container: node:buster
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Zip
        run: apt update && apt install -y zip
      - name: Install Gulp
        run: npm install --global gulp-cli
      - name: Install Dependencies
        run: npm install
      - name: Build Assets
        run: npm run build --if-present
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@master
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          exclude: "node_modules/*"
